### ISSUE TITLE
debug workflow for "why is a process so big"

### ISSUE THREAD

**Issue by cnsgsz** [google/tcmalloc#37] opened 2020-06-20 06:11 UTC
I want to inspect what is causing my program to use more memory than I expected. It seems [gperftool is deprecated in favor of abseil's tcmalloc](https://g3doc.corp.google.com/third_party/tcmalloc/g3doc/gperftools.md?cl=head) and the new go-based [pprof](https://github.com/google/pprof).

Is there a recommended workflow for inspecting what function etc is using the memory, like `HeapProfilerStart()` or `env HEAPPROFILE=/tmp/mybin.hprof` in gperftools, some flag, /heapz, etc? It seems to that I can call `absl::MallocExtension::SnapshotCurrent()`, but it returns `tcmalloc::Profile` -- is there a way to convert it to profile.proto which I assume is what the new pprof needs?

**Comment by ckennelly** [comment] 2020-06-21 04:18
Duplicate of #22

**Closed by ckennelly** 2020-06-21 04:18 UTC
